---
sr1.lab:
  hostname: 172.30.2.2
  platform: nokia_sros
  groups:
    - lab
    - nokia_sros
  data:
    site: vrnetlab
    role: pe
    type: nokia_sros
    nested_data:
      some_dict:
        a: 1
        b: 2
        some_list: [1, 2]
        s: "string"
sr2.lab:
  hostname: 172.30.2.3
  platform: nokia_sros
  groups:
    - lab
    - nokia_sros
sr3.lab:
  hostname: 172.30.2.4
  platform: nokia_sros
  groups:
    - lab
    - nokia_sros
sr4.lab:
  hostname: 172.30.2.5
  platform: nokia_sros
  groups:
#    - lab
    - nokia_sros
